### ISSUE TITLE
consistent unknown error

### ISSUE THREAD

**Issue by singularity141** [hclivess/videer#10]
sorry to bother, but when trying to use videer I always get "Error opening input files: Unknown error occurred". I've made sure to install correctly, updated and double checked avisynth+ is installed and ffmpeg & python are added to path, I've tried various combinations of settings and tried different file types and just get this error every time. not sure what to do about it. thank you

[00122.MTS.log](https://github.com/user-attachments/files/16181547/00122.MTS.log)

**Comment by hclivess** [comment]
Thanks for reporting this, can you upload the media file somewhere and share it with me?

**Comment by hclivess** [comment]
Upon closer inspection, a core plugin to handle MTS files is missing in videer. I will work on adding it.

**Comment by hclivess** [comment]
I added LSmash and it should work now (if you download code from master branch). I will publish a release later today.

**Comment by hclivess** [comment]
Please test this version and let me know if it is working https://github.com/hclivess/videer/releases/tag/1.35

**Comment by singularity141** [comment]
unfortunately it just gives the exact same error, though I've just found out it only does this when the deinterlace option is checked, so when not deinterlacing it works perfectly fine, makes an mkv file with bad interlacing, if that helps. here's the file 00122.mts I've been using above to try and deinterlace if that's what you're asking for , thanks for your patience
[https://drive.google.com/file/d/1DXxTeI5Y4QYV5j3PTDb2sXSV4DYsSJsa/view?usp=sharing](url)

**Comment by hclivess** [comment]
Thank you. I will cross-check plugin compatibility. It is possible that you will have to first do a high quality convert without deinterlacing into a more known format and then deinterlace the new file. Two operations in total.

**Comment by hclivess** [comment]
Please check that you want to use ffms2, this should resolve the issue. The default mode is only for frameserver. I will change this in the future releases.

**Comment by hclivess** [comment]
added https://github.com/hclivess/videer/blob/master/README.md#notice

**Comment by hclivess** [comment]
Also I am afraid that the issue you are experiencing is not interlacing, it is rolling shutter.
